FROM ubuntu:20.04
WORKDIR /home/maxime/Bureau/Hackaton
#Install dependecies for fastq data

RUN apt-get update && apt-get install -y \
	software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt-get install -y wget

RUN cd /usr/local/ \
&& wget https://ftp-trace.ncbi.nlm.nih.gov/sra/sdk/current/sratoolkit.current-ubuntu64.tar.gz \
&& tar -zxvf sratoolkit.current-ubuntu64.tar.gz 


#cette configuration ne peut être fait que à la main
#sratoolkit.3.0.0-ubuntu64/bin/vdb-config --interactive