FROM ubuntu:20.04

WORKDIR /home/maxime/Bureau/Hackaton
#Install dependecies for Star

RUN apt-get update && apt-get install -y \
	software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt-get install -y rna-star
